
#SRC = unity/unity.c\
#src/Stationary.c\
#test/test_Stationary.c\
#main.c

#INC = -Iunity\
#-Iinc\
#-Itest

#PROJECT_NAME = Stationary.exe

#$(PROJECT_NAME): $(SRC)
#	gcc $(SRC) $(INC) -o $(PROJECT_NAME)
#
#run:$(PROJECT_NAME)
#	./${PROJECT_NAME}
#doc:
#	make -C documentation
#
#clean:
#	rm -rf $(PROJECT_NAME) documentation/html	
#	
#
#	
	
	
	
	# Name of the project
PROJECT_NAME = even

# Output directory
BUILD = build

# All source code files
SRC = main.c\
src/evennumber.c\

# All test source files
TEST_SRC = src/evennumber.c\
test/testeven.c

TEST_OUTPUT = $(BUILD)/Test_$(PROJECT_NAME).out

# All include folders with header files
INC	= -Iinc

PROJECT_OUTPUT = $(BUILD)/$(PROJECT_NAME).out

# Default target built

	
	
	
